In [1]:
#판다스자체가 넘파이 기반으로 만들어진것
#둘이 왔다갔다 변환이 잘된다
#자유자재로 왔다갔다 할 수 있어야 함

# numpy란?
* Numerical Python 과학적, 산업적 연산을 위한 파이썬 패키지
* 다차원 배열, 행렬 연산에 주로 사용

In [2]:
# !pip install numpy
# !conda install numpyy
#판다스 깔면 자동으로 넘파이 깔리니까 따로 설치 안해줘도 됨

# 차원

* 0차원 = 점  =>스칼라 
* 1차원 = 선  =>벡터(방향을 가진 데이터)
* 2차원 = 면  => metrix, dataframe
* 3차원 = 공간, 입체  => 파일
* 4차원 = 3차원 요소가 2개 이상있는것 (숫자적으로) => 폴더 (데이터에서 말하는 차원) /현실 ->시공간

In [4]:
import numpy as np

In [5]:
a = np.array([1,2,3,4,5])

In [7]:
a

array([1, 2, 3, 4, 5])

In [6]:
a.ndim

1

In [8]:
b=32

In [9]:
b.ndim

AttributeError: 'int' object has no attribute 'ndim'

In [15]:
c = np.array([[1,2,3,4,5],[1,2,3,4,5]])

In [16]:
c

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [17]:
c.ndim

2

In [31]:
c.shape

(2, 5)

In [19]:
d= np.array([[[1,2,3,4,5],[1,2,3,4,5]],[[1,2,3,4,5],[1,2,3,4,5]]])

In [20]:
d.ndim

3

In [32]:
d.shape

(4, 2, 5)

In [24]:
e= np.array([[[[1,2,3,4,5],[1,2,3,4,5]],[[1,2,3,4,5],[1,2,3,4,5]]],[[[1,2,3,4,5],[1,2,3,4,5]],[[1,2,3,4,5],[1,2,3,4,5]]]])

In [25]:
e.ndim

4

In [33]:
e.shape

(2, 2, 2, 5)

2행5열 메트리스 2개있는게 2개 있어   젤 끝에 있는 두개 숫자가 메트리스 모양이다!

(예외)이미지 처리할때는 다르다는 것을 기억! (이미지 제외한 넘파이 차원은 뒤에 두개가 행렬ㄹ이다)

In [29]:
f= np.array([[[[[1,2,3,4,5],[1,2,3,4,5]],[[1,2,3,4,5],[1,2,3,4,5]]],[[[1,2,3,4,5],[1,2,3,4,5]],[[1,2,3,4,5],[1,2,3,4,5]]]],[[[[1,2,3,4,5],[1,2,3,4,5]],[[1,2,3,4,5],[1,2,3,4,5]]],[[[1,2,3,4,5],[1,2,3,4,5]],[[1,2,3,4,5],[1,2,3,4,5]]]]])

In [30]:
f.ndim

5

In [35]:
f.shape

(2, 2, 2, 2, 5)

In [ ]:
#1차원이 모이면 2차원이되고, 2차원이 모이면 3차원, 3차원이 모이면 4차원이 된다.

In [ ]:
#행렬연산시 크기도 잘 맞춰줘야 계산이 된다.

# numpy를 사용하는 이유 : 행렬 연산이 쉽고 빠르기 때문

* scalar

In [36]:
a= 10

In [37]:
scalar = a+1
scalar

11

* 벡터 연산

In [38]:
b= np.array([1,2,3,4,5])

In [39]:
b

array([1, 2, 3, 4, 5])

In [43]:
c= [5,6,7,8,9]

In [44]:
hap = []
temp =0
for num in c:
    hap.append(num+3)
hap

[8, 9, 10, 11, 12]

In [ ]:
#자료를 한개씩 꺼내서 더하는게 너무 귀찮다 -> 행렬 계산으로 편리하게 하자
#반복문 쓸 필요없이 간단해 진다
#행렬연산에서 벡터와 벡터 모양이 같아야 더해진다

In [47]:
b+3

array([4, 5, 6, 7, 8])

In [ ]:
#넘파이는 숫자 하나만 넣어도 알아서 복사해서 넣어줌, 곱하기도 마찬가지

In [48]:
b*8

array([ 8, 16, 24, 32, 40])

In [52]:
g=[5,6,7,8,9]

In [53]:
g+3

TypeError: can only concatenate list (not "int") to list

* 2차원 연산 +5 하기

In [55]:
d=[[1,2,3],[1,2,3],[1,2,3]]
d

[[1, 2, 3], [1, 2, 3], [1, 2, 3]]

In [60]:
hap = []
for i in d:
    temp=[]
    for j in i:
        temp.append(j+5)
    hap.append(temp)
hap

[[6, 7, 8], [6, 7, 8], [6, 7, 8]]

In [ ]:
#차원이 올라갈수록 반복문은 늘어간다
#반복문이 많이 쌓일 수록 시간이 많이 늘어난다
#하지만 넘파이 어레이는 +숫자   만하면 끝난다. 2차원이든 5차원이든 알아서 차원을 맞춰서 벡터 연산을 해준다
# 3차원만되도 중간값 묶어주고 합치는 작업 필요하다-> 이렇게하게되면 번거롭고 시간많이 들고, 복잡
#넘파이 사용하면 빨리 끝나

In [57]:
d2=np.array([[1,2,3],[1,2,3],[1,2,3]])
d2

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [56]:
d.ndim

AttributeError: 'list' object has no attribute 'ndim'

In [ ]:
#일반적 데이터 분석은 대부분 2차원 데이터를 다룬다
#주로 판다스 사용
#넘파이는  그 이상의 차원을 쓸때 사용한다
#

# numpy에서 자주 사용하는 매서드
* .ndim: 몇차원인지 보는 것
* .shape : 몇차원, 몇 행 몇 열로 되어 있는지 구조 확인
* .size : 배열 안에 있는 요소의 총 갯수가 몇 개인지
* .dtype: 데이터 타입이 무엇인지
* .itemsize: 1개 자료의크기는 몇인지

In [61]:
d2.ndim

2

In [62]:
d2.shape

(3, 3)

In [63]:
d2.size

9

In [64]:
d2.dtype

dtype('int64')

In [65]:
#item 한개의 비트 수
d2.itemsize

8

In [66]:
d3=d2/2
d3

array([[0.5, 1. , 1.5],
       [0.5, 1. , 1.5],
       [0.5, 1. , 1.5]])

In [67]:
d3.dtype

dtype('float64')

# ndarray 만들기

* np.array(리스트. 튜플)
* 자료형은 반드시 1가지만 넣는다.

In [68]:
np.array(1,2,3,4,5)

TypeError: array() takes from 1 to 2 positional arguments but 5 were given

In [ ]:
#무조건 괄호 안에 리스트나 튜플이 와야해

In [69]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [71]:
e=np.array([1,2,3,4,5])
e.dtype

dtype('int64')

In [72]:
np.array([1,2,3,4,5.3])

array([1. , 2. , 3. , 4. , 5.3])

In [74]:
e2=np.array([1,2,3,4,5.3])
print(e2.dtype)   #마지막 하나때문에 다 플롯으로 바뀌었다
print(e2)

float64
[1.  2.  3.  4.  5.3]


In [ ]:
#한개때문에 나머지도 다 바뀌어 버린다는 특징 알고있기

In [76]:
e3=np.array([1,2,'3',4,5.3])
print(e3.dtype)  #<U32  -> string을 의미하는구나
print(type(e3))
print(e3)

<U32
<class 'numpy.ndarray'>
['1' '2' '3' '4' '5.3']


In [77]:
for i in e3:
    print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


* 문자열이 제일 강력하다
* 문자>실수> 정수
* 하나로 데이터 타입 통일 된다.
* 절대 자료형 섞어서 넣지 말것 주의

파이썬에도 있는건데
* np.arange(시작, 끝+1, step)

In [79]:
np.arange(1,101)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [80]:
np.arange(3,101,3)

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
       54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [ ]:
#하나의 벡터로 만들어 진다.

* reshape(행,열) 벡터를 원하는 크기의 matrix로 변환

In [84]:
a= np.arange(24)
print(a)
print(a.ndim)
print(a.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
1
(24,)


In [85]:
#3행 8열로 만들ㄹ고 싶다면?
#[0,1,2][3,4,5]...............

In [86]:
b=a.reshape(3,8)
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [ ]:
#차원을 마음대로 늘릴 수 있다

In [89]:
b= a.reshape(3,8)
print(b)
print(b.ndim)
print(b.shape)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]
2
(3, 8)


In [91]:
c= a.reshape(3,2,2,2)
print(c)
print(c.ndim)
print(c.shape)

[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]


 [[[16 17]
   [18 19]]

  [[20 21]
   [22 23]]]]
4
(3, 2, 2, 2)


In [93]:
d=c.reshape(24,)  #다시 원상복귀
print(d)
print(d.ndim)
print(d.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
1
(24,)


In [ ]:
#나중에 이미지 데이터 분석하다보면 rgb컬러 2차원?3차원 배열로 되어있는데, 1차원으로 펼칠 수 있다고 함
#최종적으로 데이터 펼쳐서 함수에 넣게 된다
#구성도 맞아야함

In [ ]:
#1차원으로 펼치는 함수 
#.reshape
# .flatten()

* .flatten()  : 다차원 데이터를 1차원 배열로 바꿔주는 함수

In [94]:
c.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

* np.flip(데이터)  : 행렬의 순서를 뒤집을 때

In [96]:
c

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]],


       [[[16, 17],
         [18, 19]],

        [[20, 21],
         [22, 23]]]])

In [97]:
np.flip(c)

array([[[[23, 22],
         [21, 20]],

        [[19, 18],
         [17, 16]]],


       [[[15, 14],
         [13, 12]],

        [[11, 10],
         [ 9,  8]]],


       [[[ 7,  6],
         [ 5,  4]],

        [[ 3,  2],
         [ 1,  0]]]])

In [99]:
c[::-1]    #인덱싱하는 것 - 먹긴하는데 약간 결과가 다르다

array([[[[16, 17],
         [18, 19]],

        [[20, 21],
         [22, 23]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]],


       [[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]]])

## 정해진 숫자 범위 안에서 균등하게 구간을 나눌때
* np.linspace(시작, 끝, 구간 수)

In [100]:
np.linspace(0, 1, 123)

array([0.        , 0.00819672, 0.01639344, 0.02459016, 0.03278689,
       0.04098361, 0.04918033, 0.05737705, 0.06557377, 0.07377049,
       0.08196721, 0.09016393, 0.09836066, 0.10655738, 0.1147541 ,
       0.12295082, 0.13114754, 0.13934426, 0.14754098, 0.1557377 ,
       0.16393443, 0.17213115, 0.18032787, 0.18852459, 0.19672131,
       0.20491803, 0.21311475, 0.22131148, 0.2295082 , 0.23770492,
       0.24590164, 0.25409836, 0.26229508, 0.2704918 , 0.27868852,
       0.28688525, 0.29508197, 0.30327869, 0.31147541, 0.31967213,
       0.32786885, 0.33606557, 0.3442623 , 0.35245902, 0.36065574,
       0.36885246, 0.37704918, 0.3852459 , 0.39344262, 0.40163934,
       0.40983607, 0.41803279, 0.42622951, 0.43442623, 0.44262295,
       0.45081967, 0.45901639, 0.46721311, 0.47540984, 0.48360656,
       0.49180328, 0.5       , 0.50819672, 0.51639344, 0.52459016,
       0.53278689, 0.54098361, 0.54918033, 0.55737705, 0.56557377,
       0.57377049, 0.58196721, 0.59016393, 0.59836066, 0.60655

In [101]:
f = np.array([5,7,11,1,3,2,54,0.5,0.6])
f

array([ 5. ,  7. , 11. ,  1. ,  3. ,  2. , 54. ,  0.5,  0.6])

In [102]:
f.sort()   #정렬하고 싶을때

In [104]:
f

array([ 0.5,  0.6,  1. ,  2. ,  3. ,  5. ,  7. , 11. , 54. ])

In [105]:
sorted(f)

[np.float64(0.5),
 np.float64(0.6),
 np.float64(1.0),
 np.float64(2.0),
 np.float64(3.0),
 np.float64(5.0),
 np.float64(7.0),
 np.float64(11.0),
 np.float64(54.0)]

In [106]:
sorted(f, reverse =True)   #이걸 쓰는 게 좋다 #저장 되는 것

[np.float64(54.0),
 np.float64(11.0),
 np.float64(7.0),
 np.float64(5.0),
 np.float64(3.0),
 np.float64(2.0),
 np.float64(1.0),
 np.float64(0.6),
 np.float64(0.5)]

# argsort() : 자료중 값이 작은 것에서 큰 순으로 인덱스 출력

In [107]:
g= np.array([5,0.5, -7, 42, 10,0])
g

array([ 5. ,  0.5, -7. , 42. , 10. ])

In [111]:
s=g.argsort()     #숫자가 가장 작은 것들의 인덱스를 순서대로 보여준다
s

array([2, 1, 0, 4, 3])

In [114]:
print(g[s[::-1]])   #역순 정렬

[42.  10.   5.   0.5 -7. ]


# 배열 합치기
np.concatenate()

In [118]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(a)
print(a.shape) 

print(b)

[[1 2]
 [3 4]]
(2, 2)
[[5 6]
 [7 8]]


* np.concatenate((a,b)) 의 기본 병합 방향은 행방향  axis =0방향 = 행방향으로 합쳐 진다 (행이 늘어남)
* 행방향으로 합칠 때는 두 행렬의 열의 길이가 같아야 합쳐짐

In [123]:
concat_row = np.concatenate((a,b),axis=0)
print(concat_row.shape)
print(concat_row)

(4, 2)
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


* axis =1방향  =열방향으로 합쳐진다(열이 늘어남)

In [124]:
concat_col = np.concatenate((a,b),axis=1)
print(concat_col.shape)
print(concat_col)

(2, 4)
[[1 2 5 6]
 [3 4 7 8]]


In [121]:
c = np.array([[1,2],[3,4]])
d = np.array([[5,6]])  #행이 하나밖에 없는 이차원
print(c)
print(c.shape) 

print(d)
print(d.shape) 
print(c.ndim) 
print(d.ndim) 

[[1 2]
 [3 4]]
(2, 2)
[[5 6]]
(1, 2)
2
2


In [125]:
concat_row2 = np.concatenate((c,d),axis=0)
print(concat_row2 .shape)
print(concat_row2 )

(3, 2)
[[1 2]
 [3 4]
 [5 6]]


In [126]:
concat_col2 = np.concatenate((c,d),axis=1)
print(concat_col2 .shape)
print(concat_col2 )   #구성이 맞지 않으면 합쳐지지 않고 오류가 난다.

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [ ]:
e = np.array([[1,2],[3,4]])
d = np.array([[5,6]])  #행이 하나밖에 없는 이차원
print(c)
print(c.shape) 

print(d)
print(d.shape) 
print(c.ndim) 
print(d.ndim) 

## 반드시 차원이 맞아야 된다.
## 벡터와 메트리스는 합칠 수 없다.

In [ ]:
# 합치는 방향의 모양이 일치하지 않으면 합치기 불가하다

In [127]:
#개수가 안맞아서 합쳐지지 않을때 전치 행렬로 만들어서 합쳐줄 수 있다

In [ ]:
# (2,2)(1,3) -> 바꿔도 붙여지지 않음
# 어떤 방법이든 합칠 수 없음
# 어떻게 해도 붙일 수 없음
# 아예붙이는 것을 포기해야해 (구성 맞지 않으면)

# 전치 행렬 만들기
* .T
* .transpose()
* .reshape

In [128]:
print(h)
print(h.shape)

NameError: name 'h' is not defined

In [ ]:
h2=h.T
print(h2)
print(h2.shape)

In [ ]:
h3=h.transpose()
print(h3)
print(h3.shape)

In [ ]:
h4=h.reshape(3,1)
print(h4)
print(h4.shape)

In [ ]:
#shape은 꼭꼭 확인하자
#데이터분석, 딥러닝 할때 쉐입이 맞지않으면 오류가 난다

In [ ]:
np.array(6)

In [129]:
i = np.arange(6).reshape(3,2)
print(i)
print(i.shape)
print(i.ndim)

[[0 1]
 [2 3]
 [4 5]]
(3, 2)
2


In [130]:
i2=i.T
print(i2)
print(i2.shape)

[[0 2 4]
 [1 3 5]]
(2, 3)


In [132]:
i3=i.transpose()
print(i3)
print(i3.shape)

[[0 2 4]
 [1 3 5]]
(2, 3)


In [133]:
i4=i.reshape(2,3)
print(i4)
print(i4.shape)

[[0 1 2]
 [3 4 5]]
(2, 3)


In [ ]:
#리쉐입과 트렌스포즈는 다른것
#구성방법이 다르다(들어가는 방법)
#구별해서 사용하기
#리쉐입보다는 트렌스포즈로 명확하게 써주자
#순서변경은 transpose()나.T  사용하기